-- ======================================
-- SCHEMA CREATION
-- ======================================

-- 1. Personne
CREATE TABLE Personne (
    idpersonne NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR2(100) NOT NULL,
    datenaissance DATE,
    lieunaissance VARCHAR2(100),
    biographie CLOB
);

-- 2. Film
CREATE TABLE Film (
    idfilm NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre VARCHAR2(200) NOT NULL,
    annee NUMBER(4) CHECK (annee > 1800),
    description CLOB,
    idrealisateur NUMBER,
    CONSTRAINT fk_realisateur FOREIGN KEY (idrealisateur)
        REFERENCES Personne(idpersonne)
        ON DELETE SET NULL
);

-- 3. RoleFilm
CREATE TABLE RoleFilm (
    idacteur NUMBER,
    idfilm NUMBER,
    personnage VARCHAR2(100),
    PRIMARY KEY (idacteur, idfilm),
    CONSTRAINT fk_acteur FOREIGN KEY (idacteur)
        REFERENCES Personne(idpersonne)
        ON DELETE CASCADE,
    CONSTRAINT fk_film FOREIGN KEY (idfilm)
        REFERENCES Film(idfilm)
        ON DELETE CASCADE
);

-- 4. GenreFilm
CREATE TABLE GenreFilm (
    idfilm NUMBER,
    genre VARCHAR2(50),
    PRIMARY KEY (idfilm, genre),
    CONSTRAINT fk_genrefilm FOREIGN KEY (idfilm)
        REFERENCES Film(idfilm)
        ON DELETE CASCADE
);

-- ======================================
-- FAKE DATA INSERTION
-- ======================================

-- Personne
INSERT INTO Personne (nom, datenaissance, lieunaissance, biographie) 
VALUES ('Christopher Nolan', TO_DATE('1970-07-30','YYYY-MM-DD'), 'London', 'Director of blockbuster films');

INSERT INTO Personne (nom, datenaissance, lieunaissance, biographie) 
VALUES ('Leonardo DiCaprio', TO_DATE('1974-11-11','YYYY-MM-DD'), 'Los Angeles', 'Famous Hollywood actor');

INSERT INTO Personne (nom, datenaissance, lieunaissance, biographie) 
VALUES ('Kate Winslet', TO_DATE('1975-10-05','YYYY-MM-DD'), 'Reading', 'Oscar-winning actress');

INSERT INTO Personne (nom, datenaissance, lieunaissance, biographie) 
VALUES ('Steven Spielberg', TO_DATE('1946-12-18','YYYY-MM-DD'), 'Cincinnati', 'Legendary filmmaker');

INSERT INTO Personne (nom, datenaissance, lieunaissance, biographie) 
VALUES ('Tom Hanks', TO_DATE('1956-07-09','YYYY-MM-DD'), 'Concord', 'Iconic actor in many films');

-- Film
INSERT INTO Film (titre, annee, description, idrealisateur) 
VALUES ('Inception', 2010, 'A mind-bending thriller about dreams within dreams', 1);

INSERT INTO Film (titre, annee, description, idrealisateur) 
VALUES ('Titanic', 1997, 'Epic romance on the doomed ship', 4);

INSERT INTO Film (titre, annee, description, idrealisateur) 
VALUES ('Catch Me If You Can', 2002, 'True story about a master con artist', 4);

INSERT INTO Film (titre, annee, description, idrealisateur) 
VALUES ('The Terminal', 2004, 'Man stranded in an airport for months', 4);

INSERT INTO Film (titre, annee, description, idrealisateur) 
VALUES ('Dunkirk', 2017, 'World War II evacuation drama', 1);

-- RoleFilm
INSERT INTO RoleFilm (idacteur, idfilm, personnage) VALUES (2, 1, 'Dom Cobb');
INSERT INTO RoleFilm (idacteur, idfilm, personnage) VALUES (3, 2, 'Rose DeWitt Bukater');
INSERT INTO RoleFilm (idacteur, idfilm, personnage) VALUES (2, 3, 'Frank Abagnale Jr.');
INSERT INTO RoleFilm (idacteur, idfilm, personnage) VALUES (5, 4, 'Viktor Navorski');
INSERT INTO RoleFilm (idacteur, idfilm, personnage) VALUES (2, 5, 'Col. Hans');

-- GenreFilm
INSERT INTO GenreFilm (idfilm, genre) VALUES (1, 'Sci-Fi');
INSERT INTO GenreFilm (idfilm, genre) VALUES (1, 'Thriller');
INSERT INTO GenreFilm (idfilm, genre) VALUES (2, 'Romance');
INSERT INTO GenreFilm (idfilm, genre) VALUES (2, 'Drama');
INSERT INTO GenreFilm (idfilm, genre) VALUES (3, 'Biography');
INSERT INTO GenreFilm (idfilm, genre) VALUES (3, 'Crime');
INSERT INTO GenreFilm (idfilm, genre) VALUES (4, 'Comedy');
INSERT INTO GenreFilm (idfilm, genre) VALUES (4, 'Drama');
INSERT INTO GenreFilm (idfilm, genre) VALUES (5, 'War');
INSERT INTO GenreFilm (idfilm, genre) VALUES (5, 'Action');

-- Commit all changes
COMMIT;